application: shizuokago
version: 1
runtime: go
api_version: go1

handlers:
  - url: /
    static_files: static/index.html
    upload: static/index.html
  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico
  - url: /static
    static_dir: static
    application_readable: true
  - url: /slides
    static_dir: slides
    application_readable: true
  - url: /.*
    script: _go_app
